version: '3.8'

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - veritrace_network

  backend:
    build: .
    container_name: veritrace_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - instaloader_data:/root/.config/instaloader
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - veritrace_network

  celery:
    build: .
    container_name: veritrace_celery
    command: celery -A tasks.celery_worker worker --loglevel=info -Q scraping
    volumes:
      - .:/app
      - instaloader_data:/root/.config/instaloader
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - veritrace_network

networks:
  veritrace_network:
    driver: bridge

volumes:
  instaloader_data:
